[project]
name = "sts-win-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipywidgets>=8.1.8",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]
